prisma/schema.prisma
- se cambia el tipo de dato del campo min_qty_purchase de smallint a int
=> [FIX] Cambio de tipo de dato a campo min_qty_purchase

components/Navbar.js, components/atoms/Input.js, components/atoms/buttons/BurgerButton.js, components/atoms/buttons/CartButton.js
Se termina componente NavBar, y se arreglan detalles en CartButton e Input.
=> [FEATURE] se terminan componentes NavBar CardButton e Input

prisma/schema.prisma
Se modifica nombre de campo en schema images a file_image
=> [FIX] modificación schema images

components/CardsGroup.js, components/ProductCard.js, components/QtyAddCart.js, components/atoms/CardPrice.js, components/atoms/buttons/RoundButton.js, pages/index.js, styles/globals.css
se reemplaza getElementById por manejo de useState en tarjeta de producto, se arregla bordes y tamaño de imagen de producto, se agrega funcionalidad a botones de aumento y disminución de productos, se agrega componente CardsGroup para contener tarjetas de productos
=> [FEATURE] Se implementa funcionalidad de botones y agrega componente contenedor de tarjetas

pages/api/product/products.js, prisma/schema.prisma
- Si quita el include del findMany en products
- Se agrega campo isActive a product, store y producer
=> [FIX] Cambian campos del findMany de product

components/CardsGroup.js, components/Filter.js, components/ProductCard.js, pages/catalogo.js, styles/globals.css
Vista mobile completa y ajustados apartados visuales de otros componentes
=> feat: se termina vista mobile y se ajustan algunos componentes

components/ProductCard.js
se agrega nombre de productor a las tarjetas de productos
=> [FEATURE] Se agrega nombre de productor

components/Filter.js
Se soluciona problema con position Sticky que causaba que algunos elementos se posicionaran sobre el contenedor y background de filtros en la vista Mobile.
=> [FIXED] se soluciona problema con position Sticky

components/ProductCard.js, components/QtyAddCart.js, cypress/integration/shoppingCart.spec.js, pages/catalogo.js
- se corrige error en aumento y disminución de cantidad en botones
- se agrega función para aumentar y disminuir cantidad desde input
=> [FIXED] Se soluciona problemas en carrito de compras

components/Navbar.js, cypress/integration/api/product/products.spec.js, cypress/integration/infiniteScroll.spec.js, package.json, pages/api/product/[id].js, pages/api/product/products.js, pages/catalogo.js, pages/product/[id].js, yarn.lock
- Se agrega scroll infinito para el catalogo. Esta seteado de a 9 productos (se puede cambiar)
- Se uso [react-infinite-scroll-component](https://www.npmjs.com/package/react-infinite-scroll-component)
- Se agregan test respectivos
> PD: para ver el efecto, agregar mas productos en su BD local.
=> [FEATURE] Scroll infinito

pages/api/product/[id].js
- Ahora el producto buscado devuelve arreglo con todas sus imágenes
=> [FIX] productById

components/CardsGroup.js, components/ProductCard.js, pages/api/product/[id].js
- Se asigna una altura mínima para que al momento de expandir la info todas tengan el mismo tamaño
- Se realza un poco mas el box shadow para contrastar con el fondo
- Se asigna padding <CardsGroup/>
=> [BUG] Altura de las productCard

pages/api/product/[id].js, prisma/migrations/20220131164009_fk_product/migration.sql, prisma/schema.prisma
- Se crean las claves foraneas en product desde esquema prisma
=> [FIX] FK product

components/ProductCard.js, pages/api/product/[id].js, pages/api/product/products.js, prisma/migrations/20220201155043_change_name_and_delete_column/migration.sql, prisma/schema.prisma
- Se elimina campo min_qty_purchase
- Se renombra campo min_purchase a price_package
- Se obtiene el tipo de venta del productor
=> [FIXED] campos productos

next.config.js
- Prueba de configuración de variables de entorno en next.config.js
> Note: Por lo que entiendo al ser una app SSR, al momento de compilar no tiene acceso a las .env de la forma común.
=> [BUILD] env en next.config.js

package.json, prisma/client.js, yarn.lock
- Se modifica client.js, ahora solo se instancia una ves Prisma Clients por ejecución.
- Se instala `cross-env` para identificar el ambiente
=> [HOTFIX] Pool de conexion

components/ProductCard.js, components/ProductCardDesktop.js, components/atoms/QtyBox.js, cypress/integration/pageCart.spec.js, helpers/sendOrder.js, pages/carrito.js, pages/product/[slug].js
- Se agrega función en helpers para envió de de pedido por whatsApp
-  se agrega despacho en totales
=> [Feature] Se agrega envió de de pedido por whatsApp

components/Alert.js, components/Loader.js, components/Navbar.js, cypress/integration/catalogo.spec.js, cypress/integration/filter.spec.js, cypress/integration/infiniteScroll.spec.js, cypress/integration/product-detail.spec.js, cypress/integration/shoppingCart.spec.js, pages/carrito.js, pages/catalogo.js, pages/product/[slug].js, store/reducers/cartReducer.js
* Se crea componente loader
* Se condiciona la aparición de elementos en el acordeon
* Se cambian selectores de los test
=> [FEATURE] se agrega loader, se condicionan elementos de descripción

next.config.js, pages/api/category/categories.js, pages/api/product/[id].js, pages/api/product/products.js, pages/catalogo.js, pages/product/[slug].js
- Se cambia la forma de traer datos
- Se agrega configuración de webpack en next.config.js
- Se ajusta container de catalogo
=> [FIX] Api methods y next.config

.env, components/Navbar.js, pages/product/[slug].js, yarn.lock
* Se soluciona problema con navbar: se reduce su tamaño original y evitando que cambie su tamaño, además de que ahora se ejecuta una cola vez.
* Se soluciona problemas con páginas estáticas nuevas: ahora se regeneran las páginas anteriores si hay cambios en la BD y se generan nuevas si no existen.
=> [FIX] se soluciona problema con navbar y paginas staticPaths con fallback

package.json, pages/catalogo.js
Se cambia getStaticProps a getServerSideProps
=> [FIX] se cambia getStaticProps a getServerSideProps

components/Alert.js, components/ProductCard.js, components/QtyAddCart.js, components/atoms/CardPrice.js, components/atoms/buttons/RoundButton.js, cypress/integration/infiniteScroll.spec.js, cypress/integration/product-detail.spec.js, helpers/purchaseFormat.js, pages/api/product/[id].js, pages/api/product/products.js, store/reducers/producerReducer.js, styles/globals.css
* Ahora se calcula correctamente la cantidad mínima con Kilos
* Se solucionan los problemas con los test de Scroll Infinito
* Ahora la imagen por defecto es isMain
* La alerta de producto eliminado/añadido ya no aparece sin motivo
* Cambia el icono "i" a color morado y se agrega el titulo "precio por caja" al precio
* Se soluciona error emergente causado por la propiedad "disabled" de los RoundButton
* Ahora se muestra correctamente la cantidad minima cuando es en Kilos (00.1 kilos > 10 kilos)
=> [FIX] Se solucionan problemas con los calculos en kg

components/ProductCard.js, pages/carrito.js, pages/product/[slug].js, store/reducers/producerReducer.js
* Se agrega pedido mínimo del productor a la página de detalles del producto
=> [FEATURE] Pedido mínimo en página detalles de producto

cypress/integration/catalogo.spec.js, cypress/integration/infiniteScroll.spec.js, cypress/integration/product-detail.spec.js, cypress/integration/shoppingCart.spec.js, pages/carrito.js
Se corrigen problemas con test
* Scroll go up
* Botón disminuye cantidad
* página detalle de producto
* infiniteScroll
=> [FIX] Se solucionan problemas con los test

components/Navbar.js, components/QtyAddCart.js, components/atoms/buttons/BurgerButton.js, cypress/integration/addNoteOrder.spec.js, helpers/purchaseFormat.js, pages/index.js, store/reducers/producerReducer.js
Se corrige formato y calculo de venta por unidad,
Se corrige comportamiento de burgerButton
Se corrige width y type de input qtyAddButton
Se corrige descripción de test addNoteOrder
=> [FIX] Se corrige venta por unidad y burgerButton

components/ProductCardDesktop.js, pages/api/producer/products/[id].js, pages/carrito.js, pages/catalogo.js, pages/product/[slug].js, pages/productor/[id].js
- Se agrega etiqueta tittle a todas las páginas
- se corrige Links de rutas a productor
- Se corrige nombre en importación de componente QtyAddCart en [slug]
=> feature: Se agrega etiqueta tittle a todas las páginas

components/ProductCard.js, components/ProductCardDesktop.js, pages/api/producer/producers.js, pages/api/producer/products/[id].js, pages/productor/[slug].js
-Se reemplaza ID_producer por slug de productor en enlace de productor
=> style: Se reemplaza ID_producer por slug de productor en enlace de productor
